language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - CODECLIMATE_REPO_TOKEN=e67c0dd7c47251d6e30ed6db484ec5f821a3b79ff6cc9b4cdd59badcd4d4a3c6 ./vendor/bin/test-reporter
